ROTOR_dict = {
    'ROTOR_I': ['EKMFLGDQVZNTOWYHXUSPAIBRCJ', 'E'],
    'ROTOR_II': ['AJDKSIRUXBLHWTMCQGZNPYFVOE', 'E'],
    'ROTOR_III': ['BDFHJLCPRTXVZNYEIWGAKMUSQO', 'E'],
    'ROTOR_IV': ['ESOVPZJAYQUIRHXLNFTGKDCMWB', 'E'],
    'ROTOR_V': ['VZBRGITYUPSDNHLXAWMJQOFECK', 'E'],
    'ROTOR_VI': ['JPGVOUMFYQBENHZRDKASXLICTW', 'E']
}

print(ROTOR_dict['ROTOR_I'][1])